from __future__ import annotations

from typing import Any

from .. import Optimizer
from ... import Module


class AveragedModel(Module):
    def __init__(self, module: Module, *args: Any, **kwargs: Any) -> None: ...
    def update_parameters(self, module: Module) -> None: ...


class SWALR:
    def __init__(self, optimizer: Optimizer, *args: Any, **kwargs: Any) -> None: ...
    def step(self) -> None: ...
    def state_dict(self) -> Any: ...
    def load_state_dict(self, state_dict: Any) -> None: ...


def update_bn(dataloader: Any, model: Module, device: Any | None = ...) -> None: ...
