from __future__ import annotations

from typing import Any

from .. import device


def is_available() -> bool: ...

def current_device() -> int: ...

def device_count() -> int: ...

def manual_seed_all(seed: int) -> None: ...

def synchronize(device: device | int | None = ...) -> None: ...

class amp:
    class GradScaler:
        def __init__(self, *args: Any, **kwargs: Any) -> None: ...
        def scale(self, outputs: Any) -> Any: ...
        def step(self, optimizer: Any) -> None: ...
        def update(self, new_scale: float | None = ...) -> None: ...


def Stream() -> Any: ...
