from __future__ import annotations

from typing import Any

from .. import Tensor


class GradScaler:
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def scale(self, outputs: Tensor | Any) -> Any: ...
    def step(self, optimizer: Any) -> None: ...
    def update(self, new_scale: float | None = ...) -> None: ...
    def state_dict(self) -> Any: ...
    def load_state_dict(self, state_dict: Any) -> None: ...


def autocast(*args: Any, **kwargs: Any) -> Any: ...
